### ISSUE TITLE
Issue with variables for working_directory

### ISSUE THREAD

**Issue by nvmker** [RothAndrew/cf-step-pre-commit#6]
Hi,
I have following codefresh.yml:
```yaml
version: '1.0'
stages:
- prepare
- build
- test
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: openbridge/api-products
    revision: develop
    git: github
  pre_commit:
    type: rothandrew/pre-commit
    title: Validating pre-commit hooks
    stage: Validate
```
If there is no working directory set I getting following error:
```
Executing command: cd ${WORKING_DIRECTORY}
/bin/sh: 2: cd: can't cd to /codefresh/volume/${{CF_REPO_NAME}}
```
If there is working directory set to ```./${{CF_REPO_NAME}}``` I getting following error:
```
Executing command: cd ${WORKING_DIRECTORY}
/bin/sh: 2: cd: can't cd to ./${{CF_REPO_NAME}}
```
And same for just ```${{CF_REPO_NAME}}```.
Only if there is working directory set as directly as ```working_directory: ./api-products```  I getting successful runs.
